import './globals.css'
import { Inter } from 'next/font/google'
import { Roboto } from 'next/font/google'
import { Open_Sans } from 'next/font/google'
import Navbar from '@/components/Navbar'



const inter = Inter({ subsets: ['latin'] })

const roboto = Roboto({ subsets: ["latin"] ,  weight: ["100"]});


const opensans = Open_Sans({ subsets: ["latin"], weight: ["700"] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
          <Navbar />
          {children}
       
      </body>
    </html>
  );
}
