import './globals.css'
import { Inter } from 'next/font/google'
import { Roboto } from 'next/font/google'
import { Open_Sans } from 'next/font/google'
import { Lexend_Giga } from 'next/font/google'
import { Lexend_Deca } from 'next/font/google'
import Navbar from '@/components/Navbar'




const inter = Inter({ subsets: ['latin'] })

const roboto = Roboto({ subsets: ["latin"] ,  weight: ["100"]});

const lexend = Lexend_Deca({ subsets: ["latin-ext"]})

const opensans = Open_Sans({ subsets: ["latin"], weight: ["700"] });



export const metadata = {
  title: 'Tangled',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    
        <html lang="en">
          <head>
            <link
              rel="shortcut icon"
              href="favicon.ico"
              type="image/x-icon"
            ></link>
          </head>
          <body className={lexend.className}>
            <Navbar />
            {children}
          </body>
        </html>
      
  );
}
